<?php

namespace VPN;


/**
 * Trait Format
 *
 * This trait provides a set of functions for formatting configurations.
 */
trait Configurator
{
    /**
     * Formats the WireGuard server configuration.
     *
     * @param string $WireGuard Name of the WireGuard interface.
     * @param string|array $Address IP address(es) of the interface.
     * @param int $ListenPort Port to listen on.
     * @param string $PrivateKey Private key of the interface.
     * @param array $Peers Array with peer information.
     * @return string The formatted WireGuard server configuration.
     */
    public static function format_server_config(
        string       $WireGuard,
        string|array $Address,
        int          $ListenPort,
        string       $PrivateKey,
        array        $Peers,
    ): string
    {
        // Start building the configuration
        $Configuration = "# Do not edit this file manually!!!\n";
        $Configuration .= "# All changes will be overwritten!\n\n";

        // Add interface information
        $Configuration .= "[Interface]\n";
        $Configuration .= "Address = " . (is_array($Address) ? implode(', ', $Address) : $Address) . "\n";
        $Configuration .= "ListenPort = $ListenPort\n";
        $Configuration .= "PrivateKey = $PrivateKey\n";

        // Add post-up and post-down scripts to configure iptables
        // These scripts run after the interface is brought up and before it is brought down, respectively
        // They configure iptables for masquerading (NAT) and allowing traffic through the VPN
        $Configuration .= "PostUp = iptables -t nat -A POSTROUTING -o `ip route | awk '/default/ {print $5; exit}'` -j MASQUERADE\n";
        $Configuration .= "PostUp = iptables -A INPUT -p udp -m udp --dport $ListenPort -j ACCEPT\n";
        $Configuration .= "PostUp = iptables -A FORWARD -i $WireGuard -j ACCEPT\n";
        $Configuration .= "PostUp = iptables -A FORWARD -o $WireGuard -j ACCEPT\n";
        $Configuration .= "PostUp = iptables -A FORWARD -i `ip route | awk '/default/ {print $5; exit}'` -o $WireGuard -j ACCEPT\n";
        $Configuration .= "PostUp = ip rule add from `ip addr show $(ip route | awk '/default/ { print $5 }') | grep \"inet\" | grep -v \"inet6\" | head -n 1 | awk '/inet/ {print $2}' | awk -F/ '{print $1}'` table main\n";

        // Add post-down scripts to remove the iptables rules added by the post-up scripts
        // These scripts run before the interface is brought down
        // They remove the iptables rules added by the post-up scripts to restore the system to its original state
        $Configuration .= "PostDown = iptables -t nat -D POSTROUTING -o `ip route | awk '/default/ {print $5; exit}'` -j MASQUERADE\n";
        $Configuration .= "PostDown = iptables -D INPUT -p udp -m udp --dport $ListenPort -j ACCEPT\n";
        $Configuration .= "PostDown = iptables -D FORWARD -i $WireGuard -j ACCEPT\n";
        $Configuration .= "PostDown = iptables -D FORWARD -o $WireGuard -j ACCEPT\n";
        $Configuration .= "PostDown = iptables -D FORWARD -i `ip route | awk '/default/ {print $5; exit}'` -o $WireGuard -j ACCEPT\n";
        $Configuration .= "PostDown = ip rule del from `ip addr show $(ip route | awk '/default/ { print $5 }') | grep \"inet\" | grep -v \"inet6\" | head -n 1 | awk '/inet/ {print $2}' | awk -F/ '{print $1}'` table main\n";

        // Add information for each peer
        foreach ($Peers as $Peer) {
            // Comment with the peer's identifier
            $Configuration .= "\n# Client: {$Peer['Name']} ({$Peer['id']})\n";
            // Peer information
            // Peer's public key, allowed IP addresses, endpoint (if any), preshared key (if any), and keepalive interval (if any)
            $Configuration .= "[Peer]\n";
            $Configuration .= "PublicKey = {$Peer['PublicKey']}\n";
            if (isset($Peer['Address'])) {
                $Configuration .= "AllowedIPs = " . (is_array($Peer['Address']) ? implode(', ', $Peer['Address']) : $Peer['Address']) . "\n";
            }
            if (isset($Peer['PresharedKey'])) {
                $Configuration .= "PresharedKey = {$Peer['PresharedKey']}\n";
            }
        }

        return $Configuration;
    }

    /**
     * Formats the WireGuard client configuration.
     *
     * @param string $Address Client IP address.
     * @param string $PrivateKey Client private key.
     * @param array $Peers Array with peer information.
     * @param string|array|null $DNS DNS server(s) for the client to use.
     * @param int|null $MTU MTU (Maximum Transmission Unit) for the client interface.
     * @param string|null $Endpoint Endpoint for the client to connect to.
     * @param string|null $PresharedKey Preshared key for extra security.
     * @param int|null $PersistentKeepalive Interval for sending keepalive packets to maintain the connection.
     * @return string The formatted WireGuard client configuration.
     */
    public static function format_client_config(
        string            $Address,
        string            $PrivateKey,
        array             $Peers,
        string|array|null $DNS = null,
        ?int              $MTU = null,
        ?string           $Endpoint = null,
        ?string           $PresharedKey = null,
        ?int              $PersistentKeepalive = null,
    ): string
    {
        // Start building the configuration
        $Configuration = "# Configuration generated by Localzet Config Generator\n";
        $Configuration .= "[Interface]\n";
        $Configuration .= "Address = $Address\n";
        $Configuration .= "PrivateKey = $PrivateKey\n";

        // Add DNS servers, if specified
        if ($DNS !== null) {
            $Configuration .= "DNS = " . (is_array($DNS) ? implode(', ', $DNS) : $DNS) . "\n";
        }

        // Add MTU, if specified
        if ($MTU !== null) {
            $Configuration .= "MTU = $MTU\n";
        }

        // Add information for each peer
        foreach ($Peers as $Peer) {
            // Add a comment with the peer's identifier
            $Configuration .= "\n# Server: {$Peer['id']}\n";
            // Add peer information
            $Configuration .= "[Peer]\n";
            // Peer's public key
            $Configuration .= "PublicKey = {$Peer['PublicKey']}\n";
            // Allowed IP addresses for the peer
            $Configuration .= "AllowedIPs = " . (@$Peer['AllowedIPs'] ? (is_array($Peer['AllowedIPs']) ? implode(', ', $Peer['AllowedIPs']) : $Peer['AllowedIPs']) : '0.0.0.0/1, 128.0.0.0/1') . "\n";
            // Endpoint to connect to the peer
            if (isset($Peer['Endpoint']) || $Endpoint) {
                $Configuration .= "Endpoint = " . ($Peer['Endpoint'] ?? $Endpoint) . "\n";
            }
            // Preshared key for extra security
            if (isset($Peer['PresharedKey']) || $PresharedKey) {
                $Configuration .= "PresharedKey = " . ($Peer['PresharedKey'] ?? $PresharedKey) . "\n";
            }
            // Interval for sending keepalive packets to maintain the connection
            if (isset($Peer['PersistentKeepalive']) || $PersistentKeepalive) {
                $Configuration .= "PersistentKeepalive = " . ($Peer['PersistentKeepalive'] ?? $PersistentKeepalive) . "\n";
            }
        }

        return $Configuration;
    }
}
